brew "awscli"
brew "bash"
brew "bat"
brew "coreutils"
brew "curl"
brew "difftastic"
brew "fd"
brew "fzf"
brew "git"
brew "gnupg"
brew "go"
brew "grep"
brew "jq"
brew "kubectl"
brew "kubectx"
brew "lua"
brew "lua-language-server"
brew 'neovim', args: ['HEAD']
brew "podman"
brew "python"
brew "ripgrep"
brew "starship"
brew "ssh-copy-id"
brew "stow"
brew "terraform"
brew "zoxide"
brew "zsh"

cask_args appdir: "/Applications"
cask "firefox"
cask "hammerspoon"
cask "iterm2"
cask "keybase"
cask "slack"
cask "spotter"
cask "visual-studio-code"

brew "cblecker/tap/ocm"
brew "cblecker/tap/openshift-cli"

tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-nerd-font"
