brew "age"
brew "awscli"
brew "bash"
brew "bat"
brew "coreutils"
brew "curl"
brew "fd"
brew "findutils"
brew "fzf"
brew "git"
brew "gnupg"
brew "grep"
brew "jq"
brew "kubectl"
brew "kubectx"
brew 'neovim'
brew "pinentry-mac"
brew "python"
brew "ripgrep"
brew "starship"
brew "ssh-copy-id"
brew "stow"
brew "yt-dlp"
brew "zoxide"
brew "zsh"

tap "homebrew/cask"
cask_args appdir: "/Applications"
cask "discord"
cask "easy-move-plus-resize"
cask "firefox"
cask "hammerspoon"
cask "iterm2"
cask "keybase"
cask "signal"
cask "slack"
cask "visual-studio-code"

tap "helix-editor/helix"
brew "helix-editor/helix/helix"

tap "cblecker/tap"
brew "cblecker/tap/ocm"
#brew "cblecker/tap/openshift-cli"

tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-code"
cask "font-fira-mono-nerd-font"
cask "font-fontawesome"
