brew "ansible"
brew "coreutils"
brew "curl"
brew "fzf"
brew "git"
brew "go"
brew "htop"
brew "jq"
brew "kind"
brew "kubectl"
brew "kubectx"
brew "mtr"
brew 'neovim', args: ['HEAD']
brew "nmap"
brew "node"
brew "python"
brew "ripgrep"
brew "starship"
brew "ssh-copy-id"
brew "stow"
brew "terraform"
brew "tig"
brew "zsh"

cask_args appdir: "/Applications"
cask "docker"
cask "firefox"
cask "hammerspoon"
cask "iterm2"
cask "keybase"
cask "ngrok"
cask "parsec"
cask "slack"
cask "spotter"
cask "visual-studio-code"

tap "homebrew/cask-fonts"
cask "font-fira-code-nerd-font"
cask "font-fira-mono"
cask "font-fira-mono-nerd-font"
cask "font-source-code-pro"
