#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xrdb -merge ~/.Xresources

# Turn on numlock and disable it
xmodmap -e 'keycode 77 = NoSymbol Num_Lock'
numlockx on

# Tweak touchpad settings
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Drag Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Drag Lock Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" 0.7

setxkbmap -model pc105 -layout ca -variant multix -option ctrl:nocaps
pgrep compton || compton &
pgrep urxvt256c-mld || urxvt256c-mld &
feh --bg-fill ~/Pictures/Wallpapers/blue-mountains.jpg

pgrep -f watch-tag-change.sh || ~/.config/herbstluftwm/watch-tag-change.sh &

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4

TERMAPP=urxvt256c-mlc

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return spawn $TERMAPP
hc keybind $Mod-space spawn rofi -show drun
hc keybind $Mod-m spawn $TERMAPP -e ranger --selectfile=$HOME/Documents
hc keybind $Mod-b spawn qutebrowser --backend webengine
hc keybind $Mod-e spawn emacs

hc keybind XF86AudioMute spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
hc keybind XF86AudioLowerVolume spawn pactl set-sink-volume @DEFAULT_SINK@ -10%
hc keybind XF86AudioRaiseVolume spawn pactl set-sink-volume @DEFAULT_SINK@ +10%

hc keybind XF86AudioPlay spawn ~/bin/spotify-remote.sh playpause
hc keybind XF86AudioPrev spawn ~/bin/spotify-remote.sh previous
hc keybind XF86AudioNext spawn ~/bin/spotify-remote.sh next

hc keybind XF86MonBrightnessDown spawn xbacklight -10%
hc keybind XF86MonBrightnessUp spawn xbacklight +10%

# basic movement
# focusing clients
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction and focus it
hc keybind $Mod-u       chain , split bottom 0.5 , focus down
hc keybind $Mod-o       chain , split right  0.5 , focus right

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#1e88e5'
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 3
hc set frame_gap 10

hc attr theme.active.color '#1e88e5'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 3
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 3
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#1e88e5'
hc attr theme.active.outer_color '#1e88e5'
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

hc set auto_detect_monitors 1

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# kill all bars
pkill polybar

# detect primary monitor to start polybar there
PRI=$(xrandr | grep "connected primary" | cut -d\  -f1)
herbstclient pad 0 26 0 0 0
MONITOR=$PRI polybar bar &

# detect secondary monitors and start the bar there too
count=1 # start count at 1 (0 being the first monitor)
SEC_MONITORS=$(xrandr | grep \ connected | grep -v primary | cut -d\  -f1)
for monitor in $SEC_MONITORS; do
    herbstclient pad $count 40 0 0 0
    MONITOR=$monitor polybar bar &
    COUNT=$(($COUNT + 1))
done

